### ISSUE TITLE
jasper pinnings are broken

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/g2clib-feedstock#28]
### Additional comment:

@conda-forge-admin please rerender

A repo-data patch should be issued to block all previous builds to be pinnsed to `x`

**Comment by xylar** [comment]
closed via #29

**Comment by hmaarrfk** [comment]
no, a repo data patch should be opened limiting previous builds to 2.x and not allowing them to be installed side by side with 4.x


I mean. you could ignore this if you wanted to, but without the PR to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

you would always have a chance for the old g2clib + jasper4 combination

**Comment by xylar** [comment]
I see.

**Comment by xylar** [comment]
Working on it.

**Comment by xylar** [comment]
@hmaarrfk, looking at both CI and 
```
$ mamba search --info g2clib
```
I see that these older build numbers (1.7.0_0 and 1.7.0_1) were also being built with jasper 4.0.0:
```
g2clib 1.7.0 hc16b2d9_0
-----------------------
file name   : g2clib-1.7.0-hc16b2d9_0.conda
name        : g2clib
version     : 1.7.0
build       : hc16b2d9_0
build number: 0
size        : 130 KB
license     : LGPL-3.0-only
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/g2clib-1.7.0-hc16b2d9_0.conda
md5         : ccac7d1f56bbba1804c3ba8a57ed5f8f
timestamp   : 2023-03-08 22:34:16 UTC
dependencies: 
  - jasper >=2.0.25
  - jasper >=4.0.0,<5.0a0
  - libgcc-ng >=12
  - libpng >=1.6.39,<1.7.0a0
  - libzlib >=1.2.13,<1.3.0a0
  - zlib


g2clib 1.7.0 hc16b2d9_1
-----------------------
file name   : g2clib-1.7.0-hc16b2d9_1.conda
name        : g2clib
version     : 1.7.0
build       : hc16b2d9_1
build number: 1
size        : 130 KB
license     : LGPL-3.0-only
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/g2clib-1.7.0-hc16b2d9_1.conda
md5         : ec9ce534dbc8157d025e7db0b3b8f585
timestamp   : 2023-03-14 20:17:57 UTC
dependencies: 
  - jasper >=2.0.25
  - jasper >=4.0.0,<5.0a0
  - libgcc-ng >=12
  - libpng >=1.6.39,<1.7.0a0
  - libzlib >=1.2.13,<1.3.0a0
  - zlib
```
I won't deny that things were sloppy and your fix in #29 is a good move.  But I don't understand how a repodata patch is going to change the behavior of those older builds.  The problem doesn't seem to be that they were built with jasper 2.x.

**Comment by hmaarrfk** [comment]
no issues about the sloppyness. 

I'm now confused about why youwere getting the linking error in the first place.

I guess we can close this.

**Comment by xylar** [comment]
Yes, same here.  It seems like a more fundamental issue, which might actually be more concerning.
