### ISSUE TITLE
Does anyone know why "@regro-cf-autotick-bot" doesn't detect new releases?

### ISSUE THREAD

**Issue by timcera** [conda-forge/g2clib-feedstock#35]
### Comment:

Recently the nceplibs-g2c team released version 1.8.0.  The "@regro-cf-autotick-bot" didn't catch it.  The bot did catch new releases of nceplibs-ip and nceplibs-sp.  Could it be the changed name from g2clib to nceplibs-g2c?

**Comment by ocefpaf** [comment]
This is what we have in the status page:

![Screenshot from 2023-11-01 07-18-14](https://github.com/conda-forge/g2clib-feedstock/assets/950575/421ebd86-dd42-4a39-a67e-774a5717910c)

**Comment by xylar** [comment]
I would say the bot is getting confused by the older tags `g2c_v1.6.0` and `g2c_v1.5.0`.  Not sure why.

**Comment by timcera** [comment]
It thinks the version is '2c_v1.6.0' so it must be finding "-g" followed by a "2" as identifying the version.  So "nceplibs-ip" and "nceplibs-sp" work because there is no number after the dash that is misinterpreted as part of the version.

Thank you @ocefpaf for including the status page.

Now that it is pretty clear something with "@regro-cf-autotick-bot" I am going to search to see if this (or something similar) is a known bug and if not then raise it as issue.
